/**
 * Urugendo Question Document Parser
 * Highly robust parser for extracting multiple-choice questions from raw text
 * generated by PDF extraction of Rwandan traffic tests (English & Kinyarwanda).
 */

/**
 * Text normalization: strips zero-width / non-breaking spaces, normalizes
 * dashes, quotes, linebreaks, and removes document noise / page numbers.
 */
export const normalizeText = (text) => {
  if (!text || typeof text !== 'string') return '';

  return text
    // Replace non-breaking and zero-width spaces with standard space
    .replace(/[\u00A0\u1680\u2000-\u200B\u202F\u205F\u3000\uFEFF]/g, ' ')
    // Normalize typographic dashes to standard hyphen
    .replace(/[\u2010-\u2015\u2212\uFE58\uFE63\uFF0D]/g, '-')
    // Normalize curly/smart quotes
    .replace(/[\u2018\u2019\u201A\u201B]/g, "'")
    .replace(/[\u201C\u201D\u201E\u201F]/g, '"')
    // Standardize linebreaks
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n');
};

/**
 * Checks if a line is likely document metadata / page footer / noise.
 */
const isIgnorableNoiseLine = (line) => {
  const trimmed = line.trim();
  if (!trimmed) return true;
  // Page numbers like "Page 1 of 10", "Page 1 / 10", "-- 1 of 5 --", "- 1 -", "Page 1"
  if (/^--\s*\d+\s+of\s+\d+\s*--$/i.test(trimmed)) return true;
  if (/^page\s+\d+(\s*(?:of|\/)\s*\d+)?$/i.test(trimmed)) return true;
  if (/^-\s*\d+\s*-$/.test(trimmed)) return true;
  return false;
};

/**
 * Regex matching Question Headers:
 * English: Question 1, Q1, Q.1, No 1, N° 1, Item 1
 * Kinyarwanda: Ikibazo cya 1, Ikibazo cy'1, Ikibazo 1, Ibibazo 1
 * Standard: 1., 1), 1:, 1-, 1/, (1), [1]
 */
const KEYWORD_QUESTION_REGEX = /^(?:[•*]\s*|\-\s*)?(?:(?:Question|Q\.?|Ikibazo(?:\s+cya|\s+cy'?)?|Ibibazo|N[°o]\.?|Item)\s*(?:\((\d+)\)|\[(\d+)\]|(\d+))\s*(?:[\.:)\/—–\-]\s*|\s*))(.*)$/i;
const NUMBERED_QUESTION_REGEX = /^(?:[•*]\s*|\-\s*)?(?:\((\d+)\)|\[(\d+)\]|(\d+)\s*[\.:)\/—–\-])\s*(.*)$/;
const STANDALONE_Q_REGEX = /^(?:[•*]\s*|\-\s*)?(?:(?:Question|Q\.?|Ikibazo(?:\s+cya|\s+cy'?)?|Ibibazo|N[°o]\.?|Item)\s*)?(?:\((\d+)\)|\[(\d+)\]|(\d+))[\.:)\/—–\-]?\s*$/i;

/**
 * Regex matching Option Prefixes:
 * Single Option: A. Text, A) Text, (A) Text, [A] Text, A: Text, A - Text, a. Text, etc.
 * Standalone option letter: A. or (A) or A -
 */
const SINGLE_OPTION_REGEX = /^(?:[•*]\s*|\-\s*)?(?:\(([A-Ha-h])\)|\[([A-Ha-h])\]|([A-Ha-h])\s*[\.:)\/—–\-])\s*(.*)$/;
const STANDALONE_OPTION_REGEX = /^(?:[•*]\s*|\-\s*)?(?:\(([A-Ha-h])\)|\[([A-Ha-h])\]|([A-Ha-h]))[\.:)\/—–\-]?\s*$/;

/**
 * Inline multiple options on a single line:
 * e.g. "A. Stop   B. Yield   C. Go   D. None"
 */
const INLINE_OPTIONS_REGEX = /(?:^|\s+|\()([A-Ha-h])\s*[\.:)\/—–\-]\s*(.+?)(?=(?:\s+\(?[A-Ha-h]\s*[\.:)\/—–\-]\s+)|$)/g;

/**
 * Explanation / Notes
 */
const EXPLANATION_REGEX = /^(?:Explanation|Note|Ibisobanuro|Impamvu|Remarque)[\:\.]?\s*(.*)$/i;

/**
 * Extracts question number from match groups.
 */
const extractQuestionNumber = (match) => {
  if (!match) return null;
  const rawNum = match[1] || match[2] || match[3] || match[4] || match[5];
  if (!rawNum) return null;
  const num = parseInt(rawNum, 10);
  return isNaN(num) ? null : num;
};

/**
 * Helper to finalize a question and validate integrity.
 */
const finalizeQuestion = (question, currentOption) => {
  if (!question) return null;

  if (currentOption) {
    question.options.push(currentOption);
  }

  const hasText = question.questionText && question.questionText.trim().length > 0;
  const hasEnoughOptions = question.options && question.options.length >= 2;

  const reviewNotes = [];
  if (!hasText) {
    reviewNotes.push('Question prompt text is missing.');
  }
  if (!question.options || question.options.length === 0) {
    reviewNotes.push('No multiple choice options were detected.');
  } else if (question.options.length < 2) {
    reviewNotes.push('Only 1 option was detected. At least 2 options are required.');
  }

  const labels = (question.options || []).map((o) => o.label);
  const uniqueLabels = new Set(labels);
  if (uniqueLabels.size !== labels.length) {
    reviewNotes.push('Duplicate option labels detected.');
  }

  question.importStatus = (hasEnoughOptions && hasText && reviewNotes.length === 0)
    ? 'valid'
    : 'needs_review';

  question.reviewNotes = reviewNotes.join(' ');
  return question;
};

/**
 * Parses raw text line-by-line.
 */
const parseLineByLine = (cleanText) => {
  const lines = cleanText
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.length > 0 && !isIgnorableNoiseLine(l));

  const questions = [];
  let currentQuestion = null;
  let currentOption = null;

  const pushQuestion = () => {
    if (currentQuestion) {
      const finalized = finalizeQuestion(currentQuestion, currentOption);
      if (finalized) questions.push(finalized);
      currentQuestion = null;
      currentOption = null;
    }
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Check if line is Explanation/Note
    const explMatch = line.match(EXPLANATION_REGEX);
    if (explMatch && currentQuestion) {
      if (currentOption) {
        currentQuestion.options.push(currentOption);
        currentOption = null;
      }
      const note = explMatch[1]?.trim() || '';
      currentQuestion.explanation = currentQuestion.explanation
        ? `${currentQuestion.explanation} ${note}`.trim()
        : note;
      continue;
    }

    // Check if line is an Option FIRST if question is in progress
    // (Prevents options like "A. 40 km/h" or "(A) 1.5m" from being matched as a question)
    if (currentQuestion) {
      // 1. Check for multiple inline options on one line: e.g. "A. Yes  B. No"
      const inlineMatches = [...line.matchAll(INLINE_OPTIONS_REGEX)];
      if (inlineMatches.length >= 2) {
        if (currentOption) {
          currentQuestion.options.push(currentOption);
          currentOption = null;
        }
        for (const m of inlineMatches) {
          const label = m[1].toUpperCase();
          const text = m[2].trim();
          if (text) {
            currentQuestion.options.push({ label, text });
          }
        }
        continue;
      }

      // 2. Check for single option: "A. Stop", "A - Stop", "(A) Stop", etc.
      const singleOptMatch = line.match(SINGLE_OPTION_REGEX);
      if (singleOptMatch) {
        if (currentOption) {
          currentQuestion.options.push(currentOption);
          currentOption = null;
        }
        const label = (singleOptMatch[1] || singleOptMatch[2] || singleOptMatch[3]).toUpperCase();
        const text = (singleOptMatch[4] || '').trim();
        currentOption = { label, text };
        continue;
      }

      // 3. Standalone option letter: "A." or "(A)" on its own line
      const standOptMatch = line.match(STANDALONE_OPTION_REGEX);
      if (standOptMatch) {
        if (currentOption) {
          currentQuestion.options.push(currentOption);
          currentOption = null;
        }
        const label = (standOptMatch[1] || standOptMatch[2] || standOptMatch[3]).toUpperCase();
        currentOption = { label, text: '' };
        continue;
      }
    }

    // Check for Question Header
    // A) Keyword-prefixed: "Question 1: ...", "Ikibazo cya 1: ...", "Q1: ..."
    let qNum = null;
    let textAfterNum = '';

    const keywordMatch = line.match(KEYWORD_QUESTION_REGEX);
    if (keywordMatch) {
      qNum = extractQuestionNumber(keywordMatch);
      textAfterNum = (keywordMatch[4] || '').trim();
    } else {
      // B) Numbered: "1. ...", "1) ...", "1 - ...", "(1) ..."
      const numMatch = line.match(NUMBERED_QUESTION_REGEX);
      if (numMatch) {
        qNum = extractQuestionNumber(numMatch);
        textAfterNum = (numMatch[4] || '').trim();
      } else {
        // C) Standalone question number on its own line: "1.", "1)", "Question 1"
        const standMatch = line.match(STANDALONE_Q_REGEX);
        if (standMatch) {
          qNum = extractQuestionNumber(standMatch);
          textAfterNum = '';
        }
      }
    }

    if (qNum !== null && qNum > 0) {
      // Start a new question
      pushQuestion();
      currentQuestion = {
        questionNumber: qNum,
        sourceQuestionNumber: qNum,
        questionText: textAfterNum,
        options: [],
        correctOption: '',
        explanation: '',
        importStatus: 'needs_review',
        reviewNotes: '',
        approved: false,
      };
      continue;
    }

    // If no active question yet, this may be cover page or preamble text
    if (!currentQuestion) {
      continue;
    }

    // Continuation lines:
    if (currentOption) {
      // Append line to current option text
      currentOption.text = currentOption.text ? `${currentOption.text} ${line}` : line;
    } else if (currentQuestion.options.length === 0) {
      // Append line to question prompt text
      currentQuestion.questionText = currentQuestion.questionText
        ? `${currentQuestion.questionText} ${line}`
        : line;
    } else if (currentQuestion.explanation) {
      // Append to explanation
      currentQuestion.explanation += ` ${line}`;
    } else {
      // Append to last option
      const lastOpt = currentQuestion.options[currentQuestion.options.length - 1];
      if (lastOpt) {
        lastOpt.text += ` ${line}`;
      }
    }
  }

  // Push final question
  pushQuestion();
  return questions;
};

/**
 * Fallback block-based parser:
 * Scans entire text for question blocks using global regex if line-by-line yields 0 questions.
 */
const parseBlockByBlock = (cleanText) => {
  const blockRegex = /(?:^|\n)(?:(?:[•*]\s*|\-\s*)?(?:(?:Question|Q\.?|Ikibazo(?:\s+cya|\s+cy'?)?|Ibibazo|N[°o]\.?|Item)\s*(?:\((\d+)\)|\[(\d+)\]|(\d+))\s*(?:[\.:)\/—–\-]\s*|\s*))|(?:\((\d+)\)|\[(\d+)\]|(\d+)\s*[\.:)\/—–\-])\s*)([\s\S]+?)(?=(?:\n(?:[•*]\s*|\-\s*)?(?:(?:Question|Q\.?|Ikibazo(?:\s+cya|\s+cy'?)?|Ibibazo|N[°o]\.?|Item)\s*(?:\(\d+\)|\[\d+\]|\d+)\s*(?:[\.:)\/—–\-]\s*|\s*)|(?:\(\d+\)|\[\d+\]|\d+\s*[\.:)\/—–\-])\s*))|$)/gi;

  const matches = [...cleanText.matchAll(blockRegex)];
  if (matches.length === 0) return [];

  const questions = [];
  for (const match of matches) {
    const qNum = parseInt(match[1] || match[2] || match[3] || match[4] || match[5] || match[6], 10);
    const blockContent = (match[7] || '').trim();

    if (isNaN(qNum) || !blockContent) continue;

    const blockLines = blockContent.split('\n').map((l) => l.trim()).filter(Boolean);
    const question = {
      questionNumber: qNum,
      sourceQuestionNumber: qNum,
      questionText: '',
      options: [],
      correctOption: '',
      explanation: '',
      importStatus: 'needs_review',
      reviewNotes: '',
      approved: false,
    };

    let currentOption = null;

    for (const bLine of blockLines) {
      // Check inline options
      const inlineMatches = [...bLine.matchAll(INLINE_OPTIONS_REGEX)];
      if (inlineMatches.length >= 2) {
        if (currentOption) {
          question.options.push(currentOption);
          currentOption = null;
        }
        for (const m of inlineMatches) {
          question.options.push({ label: m[1].toUpperCase(), text: m[2].trim() });
        }
        continue;
      }

      // Check single option
      const optMatch = bLine.match(SINGLE_OPTION_REGEX);
      if (optMatch) {
        if (currentOption) {
          question.options.push(currentOption);
          currentOption = null;
        }
        const label = (optMatch[1] || optMatch[2] || optMatch[3]).toUpperCase();
        currentOption = { label, text: (optMatch[4] || '').trim() };
        continue;
      }

      // Check continuation
      if (currentOption) {
        currentOption.text += ` ${bLine}`;
      } else if (question.options.length === 0) {
        question.questionText = question.questionText ? `${question.questionText} ${bLine}` : bLine;
      }
    }

    const finalized = finalizeQuestion(question, currentOption);
    if (finalized) {
      questions.push(finalized);
    }
  }

  return questions;
};

/**
 * Main Question Parser export
 * @param {string} rawText - Raw text extracted from PDF
 * @returns {Array<object>} Array of structured question objects
 */
export const parseQuestions = (rawText) => {
  if (!rawText || typeof rawText !== 'string') {
    return [];
  }

  const cleanText = normalizeText(rawText);
  if (!cleanText.trim()) {
    return [];
  }

  // Strategy 1: Line-by-line parsing
  const questions = parseLineByLine(cleanText);
  if (questions.length > 0) {
    return questions;
  }

  // Strategy 2: Fallback block parsing
  return parseBlockByBlock(cleanText);
};

export default {
  parseQuestions,
  normalizeText,
};
